# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hungerstation
# ---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: app-config
  namespace: hungerstation
data:
  REDIS_HOST: {{ .Values.redisPort.host }} 
  REDIS_PORT: {{ .Values.redisPort.backendPort | quote }} 