# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hungerstation
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-deployment
  namespace: hungerstation
  labels:
     name: redis-pod
     app: backend
spec:
  selector:
    matchLabels:
      name: redis-pod
      app: backend
  serviceName: redis
  replicas: 1
  template:
    metadata:
      name: redis-pod 
      labels:
        name: redis-pod
        app: backend
    spec:
      containers:
      - name: redis-container
        image: {{ .Values.image.repositoryRedis }}
        ports:
        - containerPort: {{ .Values.redisPort.backendPort }} 
        resources:
           requests:
               memory: {{ .Values.resourceMemory.request.rmemory | quote }}                  
               cpu: {{ .Values.resourceMemory.request.rcpu }}                          
           limits:
              memory: {{ .Values.resourceMemory.limit.lmemory | quote }}                   
              cpu: {{ .Values.resourceMemory.limit.lcpu }}
        livenessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
        readinessProbe:
            exec:
              command:
              - redis-cli
              - ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: hungerstation
  labels:
    name: redis-service
spec:
  ports:
  - port: {{ .Values.redisPort.backendPort }}
    name: redis-something
    targetPort: {{ .Values.redisPort.backendPort }}
  selector:
     name: redis-pod
     app: backend
  clusterIP: None