# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hungerstation
# ---
apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
  namespace: hungerstation
data:
  USERNAME: Ym9i
  PASSWORD: YnVpbGRlcg==
  THEBIGSECRET: SSBsb3ZlIGNvb2tpZXMu