apiVersion: v1
kind: Namespace
metadata:
  name: hungerstation
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-autoscaler-webapp
  namespace: hungerstation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployment-autoscaler-redis
  namespace: hungerstation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
